external fun foo(f: Fun<Int, Int>): Int {
    f(1)
}

// args: check
// expected exit status: 1
// expected stdout:
// Error: Expected a tuple here, e.g. `Fun<(Int, Int), String>` but got `Int`.
// ---| src/test_files/check/malformed_function_parameter.gdn:1:25
//   1| external fun foo(f: Fun<Int, Int>): Int {
//   2|     f(1)                ^^^
//   3| }

