external fun foo(): List<Int, Int, Int> {
    error("")
}

// args: check
// expected exit status: 1
// expected stdout:
// Error: List takes 1 type argument, but got 3 arguments.
// --| src/test_files/check/type_arg_arity.gdn:1:36
// external fun foo(): List<Int, Int, Int> {
//                                    ^^^

